version: "3.8"
services:

    marketplace:
        build:
            context: .
            dockerfile: marketplace/Dockerfile
        environment:
            # RECOMMENDATIONS_HOST: "localhost"
            RECOMMENDATIONS_HOST: recommendations
        image: marketplace
        networks:
            - microservices
        ports:
            - 8000:5000

    recommendations:
        build:
            context: .
            dockerfile: recommendations/Dockerfile
        environment:
            DB_PATH: "../database/db.json"
        image: recommendations
        networks:
            - microservices

networks:
    microservices:
